appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.2.3
appReplicas: 2
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "7000"

servicePort: 7000
serviceType: ClusterIP
